import { db } from "./db";
import { persons, documents, connections, personDocuments, timelineEvents } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  const [existingDocs] = await db.select({ count: sql<number>`count(*)::int` }).from(documents);
  if (existingDocs.count > 0) {
    return;
  }

  console.log("Seeding database with Epstein files data...");

  const [existingPersons] = await db.select({ count: sql<number>`count(*)::int` }).from(persons);
  const hasPersons = existingPersons.count > 0;

  const personData = [
    {
      name: "Jeffrey Epstein",
      aliases: ["Jeffrey Edward Epstein"],
      role: "Central figure",
      description: "American financier and convicted sex offender who ran a sex trafficking operation. Arrested in July 2019 and found dead in his jail cell in August 2019. Subject of the Epstein Files Transparency Act.",
      status: "deceased",
      nationality: "American",
      occupation: "Financier",
      documentCount: 47,
      connectionCount: 18,
      category: "key figure",
    },
    {
      name: "Ghislaine Maxwell",
      aliases: ["Ghislaine Noelle Marion Maxwell"],
      role: "Co-conspirator",
      description: "British socialite convicted of sex trafficking and conspiracy. Found guilty in December 2021 on five of six counts. Sentenced to 20 years in federal prison. Her defamation case led to the initial unsealing of documents.",
      status: "convicted",
      nationality: "British",
      occupation: "Socialite",
      documentCount: 38,
      connectionCount: 15,
      category: "key figure",
    },
    {
      name: "Bill Clinton",
      aliases: ["William Jefferson Clinton"],
      role: "Named individual",
      description: "42nd President of the United States. Appeared in flight logs for Epstein's private aircraft. Photographed with Epstein and Maxwell. No accusations of misconduct involving minors were made in the released documents.",
      status: "named",
      nationality: "American",
      occupation: "Former U.S. President",
      documentCount: 12,
      connectionCount: 6,
      category: "political",
    },
    {
      name: "Donald Trump",
      aliases: ["Donald John Trump"],
      role: "Named individual",
      description: "45th and 47th President of the United States. Named in documents primarily in the context of social interactions. Photos found with Maxwell. Signed the Epstein Files Transparency Act in November 2025.",
      status: "named",
      nationality: "American",
      occupation: "Former/Current U.S. President",
      documentCount: 9,
      connectionCount: 5,
      category: "political",
    },
    {
      name: "Prince Andrew",
      aliases: ["Andrew, Duke of York", "Andrew Windsor"],
      role: "Named individual",
      description: "Member of the British Royal Family. Subject of civil lawsuit by Virginia Giuffre. Settled the case in February 2022. Named in numerous flight logs and witness depositions. Stripped of military titles and royal patronages.",
      status: "named",
      nationality: "British",
      occupation: "Royal Family Member",
      documentCount: 22,
      connectionCount: 8,
      category: "key figure",
    },
    {
      name: "Virginia Giuffre",
      aliases: ["Virginia Roberts", "Virginia Roberts Giuffre"],
      role: "Victim / Key witness",
      description: "Key accuser who filed a civil lawsuit against Ghislaine Maxwell for defamation. Her testimony and depositions were central to many of the unsealed documents. Alleged she was trafficked to multiple prominent individuals.",
      status: "victim",
      nationality: "American",
      occupation: "Advocate",
      documentCount: 28,
      connectionCount: 10,
      category: "victim",
    },
    {
      name: "Alan Dershowitz",
      aliases: [],
      role: "Named individual",
      description: "Prominent attorney and Harvard Law professor. Part of Epstein's legal defense team. Named in victim testimonies. Vigorously denied all allegations and filed countersuits. Provided legal counsel during 2008 plea deal.",
      status: "named",
      nationality: "American",
      occupation: "Attorney / Law Professor",
      documentCount: 18,
      connectionCount: 7,
      category: "legal",
    },
    {
      name: "Jean-Luc Brunel",
      aliases: [],
      role: "Associate",
      description: "French modeling agent. Accused of procuring young women for Epstein through his modeling agencies. Found dead in his prison cell in Paris in February 2022 while awaiting trial on rape and sex trafficking charges.",
      status: "deceased",
      nationality: "French",
      occupation: "Modeling Agent",
      documentCount: 11,
      connectionCount: 5,
      category: "key figure",
    },
    {
      name: "Sarah Kellen",
      aliases: ["Sarah Kellen Vickers"],
      role: "Employee / Associate",
      description: "Former assistant to Jeffrey Epstein. Named in multiple victim statements as having scheduled appointments and recruited victims. Identified as one of four co-conspirators given immunity in the 2008 plea agreement.",
      status: "named",
      nationality: "American",
      occupation: "Personal Assistant",
      documentCount: 14,
      connectionCount: 6,
      category: "associate",
    },
    {
      name: "Les Wexner",
      aliases: ["Leslie Herbert Wexner"],
      role: "Business associate",
      description: "Billionaire businessman and founder of L Brands (Victoria's Secret parent company). Was Epstein's most prominent financial client. Gave Epstein power of attorney over his finances. Transferred his Manhattan mansion to Epstein.",
      status: "named",
      nationality: "American",
      occupation: "Businessman / CEO",
      documentCount: 8,
      connectionCount: 4,
      category: "associate",
    },
    {
      name: "Alexander Acosta",
      aliases: [],
      role: "Legal figure",
      description: "Former U.S. Attorney who oversaw Epstein's controversial 2008 plea deal in Florida. Later served as U.S. Secretary of Labor. Resigned in 2019 after renewed scrutiny of the lenient plea agreement he authorized.",
      status: "named",
      nationality: "American",
      occupation: "Attorney / Former Secretary of Labor",
      documentCount: 7,
      connectionCount: 4,
      category: "legal",
    },
    {
      name: "Kevin Spacey",
      aliases: ["Kevin Spacey Fowler"],
      role: "Named individual",
      description: "Actor photographed with Epstein and Maxwell. Appeared in photographs released in the DOJ document disclosures. Named in flight logs as a passenger on Epstein's aircraft.",
      status: "named",
      nationality: "American",
      occupation: "Actor",
      documentCount: 4,
      connectionCount: 3,
      category: "associate",
    },
    {
      name: "David Copperfield",
      aliases: ["David Seth Kotkin"],
      role: "Named individual",
      description: "Magician and illusionist. Photographed with Ghislaine Maxwell in released documents. Named in Virginia Giuffre's testimony as someone she was introduced to by Epstein, though Copperfield denied wrongdoing.",
      status: "named",
      nationality: "American",
      occupation: "Magician / Entertainer",
      documentCount: 3,
      connectionCount: 2,
      category: "associate",
    },
    {
      name: "Nadia Marcinkova",
      aliases: ["Nadia Marcinko", "Global Girl"],
      role: "Victim / Associate",
      description: "Reportedly brought to the U.S. from Eastern Europe by Epstein as a teenager. Later became a pilot and was named as both a victim and someone who participated in abuse according to victim statements. Given immunity in 2008 deal.",
      status: "named",
      nationality: "Slovakian-American",
      occupation: "Pilot",
      documentCount: 10,
      connectionCount: 5,
      category: "associate",
    },
    {
      name: "Johanna Sjoberg",
      aliases: [],
      role: "Victim / Witness",
      description: "College student recruited by Sarah Kellen to work as Epstein's assistant. Provided key deposition testimony describing interactions at Epstein's residences. Testified about encounters involving Prince Andrew.",
      status: "victim",
      nationality: "American",
      occupation: "Student (at time)",
      documentCount: 8,
      connectionCount: 4,
      category: "victim",
    },
    {
      name: "Bill Richardson",
      aliases: ["William Blaine Richardson III"],
      role: "Named individual",
      description: "Former Governor of New Mexico and U.S. Secretary of Energy. Named in victim depositions as someone they were directed to provide services to. Richardson denied all allegations before his death in 2023.",
      status: "deceased",
      nationality: "American",
      occupation: "Politician / Governor",
      documentCount: 5,
      connectionCount: 3,
      category: "political",
    },
    {
      name: "George Mitchell",
      aliases: [],
      role: "Named individual",
      description: "Former U.S. Senate Majority Leader and special envoy. Named in victim testimonies. Denied all allegations of improper conduct. Referenced in unsealed Maxwell defamation case documents.",
      status: "named",
      nationality: "American",
      occupation: "Politician / Senator",
      documentCount: 4,
      connectionCount: 3,
      category: "political",
    },
    {
      name: "Adriana Ross",
      aliases: [],
      role: "Employee / Associate",
      description: "Former Epstein employee. Named as one of four co-conspirators granted immunity in the 2008 non-prosecution agreement. Invoked Fifth Amendment during deposition testimony in the Maxwell defamation case.",
      status: "named",
      nationality: "Polish-American",
      occupation: "Personal Assistant",
      documentCount: 6,
      connectionCount: 4,
      category: "associate",
    },
    {
      name: "Lesley Groff",
      aliases: [],
      role: "Employee",
      description: "Long-time executive assistant to Jeffrey Epstein. Named as one of four co-conspirators given immunity in the 2008 plea deal. Described as managing Epstein's schedule and household operations.",
      status: "named",
      nationality: "American",
      occupation: "Executive Assistant",
      documentCount: 7,
      connectionCount: 3,
      category: "associate",
    },
    {
      name: "Steve Bannon",
      aliases: ["Stephen Kevin Bannon"],
      role: "Named individual",
      description: "Former White House Chief Strategist. Photos found on his phone showing Trump with Ghislaine Maxwell were included in DOJ document releases. Referenced in disclosure materials.",
      status: "named",
      nationality: "American",
      occupation: "Political Strategist",
      documentCount: 3,
      connectionCount: 2,
      category: "political",
    },
  ];

  const createdPersons = [];
  for (const p of personData) {
    if (hasPersons) {
      const [existing] = await db
        .select()
        .from(persons)
        .where(sql`LOWER(${persons.name}) = LOWER(${p.name})`)
        .limit(1);

      if (existing) {
        await db.update(persons).set({
          aliases: p.aliases,
          role: p.role,
          description: p.description,
          status: p.status,
          nationality: p.nationality,
          occupation: p.occupation,
          documentCount: p.documentCount,
          connectionCount: p.connectionCount,
          category: p.category,
        }).where(sql`id = ${existing.id}`);
        createdPersons.push(existing);
        continue;
      }
    }
    const [created] = await db.insert(persons).values(p).returning();
    createdPersons.push(created);
  }

  const documentData = [
    {
      title: "Epstein Flight Logs - Lolita Express",
      description: "Complete flight logs for Jeffrey Epstein's private Boeing 727-31, tail number N908JE, nicknamed the 'Lolita Express'. Records passenger manifests, dates, and destinations.",
      documentType: "flight log",
      dataSet: "1",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-1-files",
      datePublished: "2025-12-19",
      dateOriginal: "1995-2013",
      pageCount: 73,
      isRedacted: true,
      keyExcerpt: "Flight manifests document hundreds of trips between Teterboro, NJ, Palm Beach, FL, the U.S. Virgin Islands, and international destinations.",
      tags: ["flight logs", "travel", "passenger manifest"],
    },
    {
      title: "Virginia Giuffre Deposition - Maxwell Defamation Case",
      description: "Sworn deposition testimony of Virginia Roberts Giuffre in the defamation lawsuit against Ghislaine Maxwell, describing recruitment and trafficking allegations.",
      documentType: "deposition",
      dataSet: "2",
      sourceUrl: "https://www.justice.gov/epstein/court-records",
      datePublished: "2024-01-03",
      dateOriginal: "2016-05-03",
      pageCount: 334,
      isRedacted: true,
      keyExcerpt: "I was recruited at Mar-a-Lago by Ghislaine Maxwell when I was working there as a spa attendant. I was 15 years old.",
      tags: ["deposition", "victim testimony", "Maxwell case"],
    },
    {
      title: "Ghislaine Maxwell Deposition Transcript",
      description: "Sealed deposition of Ghislaine Maxwell taken during the Virginia Giuffre defamation case. Maxwell denied all allegations of involvement in sex trafficking.",
      documentType: "deposition",
      dataSet: "2",
      sourceUrl: "https://www.justice.gov/epstein/court-records",
      datePublished: "2024-01-03",
      dateOriginal: "2016-04-22",
      pageCount: 418,
      isRedacted: true,
      keyExcerpt: "Maxwell testified that she had 'no recollection' of many events described by Giuffre and denied any involvement in procuring minors.",
      tags: ["deposition", "Maxwell", "denial"],
    },
    {
      title: "2008 Non-Prosecution Agreement (NPA)",
      description: "Controversial plea deal between Jeffrey Epstein and federal prosecutors in the Southern District of Florida, overseen by U.S. Attorney Alexander Acosta. Granted immunity to unnamed co-conspirators.",
      documentType: "court filing",
      dataSet: "3",
      sourceUrl: "https://www.justice.gov/epstein/court-records",
      datePublished: "2025-12-19",
      dateOriginal: "2008-06-30",
      pageCount: 18,
      isRedacted: false,
      keyExcerpt: "The agreement provided immunity from federal prosecution for Epstein and any potential co-conspirators, in exchange for a guilty plea to state prostitution charges.",
      tags: ["plea deal", "NPA", "Acosta", "immunity"],
    },
    {
      title: "FBI Interview Reports - Victim Statements (302s)",
      description: "FBI Form 302 interview summaries documenting statements from multiple victims describing their recruitment and experiences at Epstein's properties.",
      documentType: "fbi report",
      dataSet: "4",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-4-files",
      datePublished: "2026-01-30",
      dateOriginal: "2006-2019",
      pageCount: 156,
      isRedacted: true,
      keyExcerpt: "Multiple victims described a similar pattern of recruitment: approached by young women, offered money for massages, then subjected to escalating sexual abuse.",
      tags: ["FBI", "victim statements", "302", "interviews"],
    },
    {
      title: "Epstein's Black Book - Contact Directory",
      description: "Jeffrey Epstein's personal contact book containing names, phone numbers, and addresses of hundreds of individuals. Circled entries reportedly indicated closer connections.",
      documentType: "contact list",
      dataSet: "1",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-1-files",
      datePublished: "2025-12-19",
      dateOriginal: "2004-2005",
      pageCount: 97,
      isRedacted: true,
      keyExcerpt: "The contact book contained over 1,500 names with phone numbers, including numerous prominent figures in business, entertainment, politics, and science.",
      tags: ["contact list", "black book", "names"],
    },
    {
      title: "Grand Jury Transcripts - Southern District of New York",
      description: "Grand jury proceedings from the SDNY investigation that led to Epstein's 2019 arrest on federal sex trafficking charges. Heavily redacted per grand jury secrecy rules.",
      documentType: "court filing",
      dataSet: "5",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-5-files",
      datePublished: "2025-12-19",
      dateOriginal: "2019-07-01",
      pageCount: 119,
      isRedacted: true,
      keyExcerpt: "[REDACTED - Grand jury material subject to Rule 6(e) protections]",
      tags: ["grand jury", "SDNY", "redacted", "2019 indictment"],
    },
    {
      title: "Surveillance Footage Summary - MCC New York",
      description: "Summary and still frames from surveillance cameras at the Metropolitan Correctional Center in Manhattan from the night of Epstein's death on August 10, 2019.",
      documentType: "fbi report",
      dataSet: "8",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-8-files",
      datePublished: "2026-01-30",
      dateOriginal: "2019-08-10",
      pageCount: 34,
      isRedacted: true,
      keyExcerpt: "Surveillance footage from cameras near Epstein's cell showed no one entering or leaving the tier during the relevant timeframe. Two cameras malfunctioned.",
      tags: ["surveillance", "MCC", "death", "cameras"],
    },
    {
      title: "Johanna Sjoberg Deposition Transcript",
      description: "Deposition testimony of Johanna Sjoberg describing her time working for Epstein, including encounters with Prince Andrew and other prominent individuals at Epstein's New York residence.",
      documentType: "deposition",
      dataSet: "2",
      sourceUrl: "https://www.justice.gov/epstein/court-records",
      datePublished: "2024-01-03",
      dateOriginal: "2016-05-19",
      pageCount: 198,
      isRedacted: true,
      keyExcerpt: "Sjoberg described being photographed sitting on Prince Andrew's lap while he held a puppet of himself.",
      tags: ["deposition", "witness", "Prince Andrew"],
    },
    {
      title: "Epstein Property Search Warrants and Inventories",
      description: "Search warrant applications and inventory lists from FBI raids on Epstein's properties including his Manhattan mansion, Palm Beach estate, and private island.",
      documentType: "court filing",
      dataSet: "6",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-6-files",
      datePublished: "2026-01-30",
      dateOriginal: "2019-07-06",
      pageCount: 87,
      isRedacted: true,
      keyExcerpt: "Agents recovered CDs labeled with names and dates, hundreds of photographs, a fake Austrian passport with Epstein's photo under a different name, and piles of cash and diamonds.",
      tags: ["search warrant", "property", "evidence", "raid"],
    },
    {
      title: "Financial Records - Wire Transfers and Bank Statements",
      description: "Banking records showing wire transfers between Epstein's accounts and various individuals and entities, including payments to potential victims and associates.",
      documentType: "financial record",
      dataSet: "7",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-7-files",
      datePublished: "2026-01-30",
      dateOriginal: "2002-2019",
      pageCount: 245,
      isRedacted: true,
      keyExcerpt: "Records show systematic payments to young women, typically ranging from $200 to $500 per visit, as well as larger transfers to associates and legal counsel.",
      tags: ["financial", "bank records", "wire transfers", "payments"],
    },
    {
      title: "Epstein-Maxwell Email Correspondence",
      description: "Email exchanges between Jeffrey Epstein and Ghislaine Maxwell recovered from seized electronic devices, discussing travel arrangements, social events, and personal matters.",
      documentType: "email",
      dataSet: "9",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-9-files",
      datePublished: "2026-01-30",
      dateOriginal: "2005-2015",
      pageCount: 312,
      isRedacted: true,
      keyExcerpt: "Maxwell wrote to Epstein after the 2008 plea deal: 'You have done nothing wrong and I would urge you to start acting like it.'",
      tags: ["email", "correspondence", "Maxwell", "communications"],
    },
    {
      title: "Photographs from Epstein Properties",
      description: "Collection of photographs seized from Epstein's Manhattan mansion and other properties during 2019 FBI raids, showing Epstein with various public figures at social events.",
      documentType: "photograph",
      dataSet: "10",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-10-files",
      datePublished: "2026-01-30",
      dateOriginal: "1990-2019",
      pageCount: 0,
      isRedacted: true,
      keyExcerpt: "Photos include images of Bill Clinton, Kevin Spacey, and Ghislaine Maxwell with David Copperfield, as well as interior shots of Epstein's properties.",
      tags: ["photographs", "evidence", "seized property"],
    },
    {
      title: "Victim Impact Statements - SDNY Sentencing",
      description: "Statements from victims submitted during the Southern District of New York proceedings, describing the long-term impact of Epstein's crimes on their lives.",
      documentType: "court filing",
      dataSet: "3",
      sourceUrl: "https://www.justice.gov/epstein/court-records",
      datePublished: "2025-12-19",
      dateOriginal: "2019-08-27",
      pageCount: 64,
      isRedacted: true,
      keyExcerpt: "Over thirty victims prepared statements for the court hearing that was scheduled after Epstein's death, expressing anger and grief at being denied justice.",
      tags: ["victim impact", "sentencing", "SDNY"],
    },
    {
      title: "House Oversight Committee Report - Epstein Records",
      description: "Report from the House Committee on Oversight and Government Reform compiling records provided by the Department of Justice, including previously unreleased materials.",
      documentType: "court filing",
      dataSet: "11",
      sourceUrl: "https://oversight.house.gov/release/oversight-committee-releases-epstein-records-provided-by-the-department-of-justice/",
      datePublished: "2025-09-01",
      dateOriginal: "2025-09-01",
      pageCount: 33295,
      isRedacted: true,
      keyExcerpt: "The committee released 33,295 pages of records including documents and surveillance video from the night of Epstein's death and court filings from Maxwell case.",
      tags: ["congressional", "oversight", "House committee"],
    },
    {
      title: "Fake Austrian Passport Documentation",
      description: "FBI analysis of the counterfeit Austrian passport found during the search of Epstein's Manhattan mansion, bearing his photograph under a false name with stamps from multiple countries.",
      documentType: "fbi report",
      dataSet: "6",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-6-files",
      datePublished: "2026-01-30",
      dateOriginal: "2019-07-08",
      pageCount: 12,
      isRedacted: false,
      keyExcerpt: "The passport bore Epstein's photograph but listed a false name and a Saudi Arabian address. It contained entry stamps from France, Spain, the United Kingdom, and Austria from the 1980s.",
      tags: ["passport", "fake identity", "evidence"],
    },
    {
      title: "Epstein-Les Wexner Financial Power of Attorney",
      description: "Legal documents showing the broad power of attorney that billionaire Les Wexner granted to Jeffrey Epstein over his financial affairs, and the subsequent transfer of the Manhattan mansion.",
      documentType: "financial record",
      dataSet: "7",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-7-files",
      datePublished: "2026-01-30",
      dateOriginal: "1998-2007",
      pageCount: 28,
      isRedacted: false,
      keyExcerpt: "Wexner granted Epstein sweeping authority over his financial affairs including the ability to hire and fire employees, sign checks, and manage investments worth hundreds of millions.",
      tags: ["financial", "Wexner", "power of attorney", "mansion"],
    },
    {
      title: "Maxwell Trial Exhibits - Government Evidence List",
      description: "Compiled list and select exhibits from the United States v. Ghislaine Maxwell trial in December 2021, including photographs, flight logs excerpts, and communications.",
      documentType: "court filing",
      dataSet: "12",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-12-files",
      datePublished: "2026-01-30",
      dateOriginal: "2021-12-01",
      pageCount: 892,
      isRedacted: true,
      keyExcerpt: "Prosecution presented evidence showing Maxwell played a central role in identifying, befriending, and grooming minor victims for Epstein's sexual abuse.",
      tags: ["trial", "Maxwell", "exhibits", "prosecution"],
    },
    {
      title: "Epstein Island Property Records - Little St. James",
      description: "Property records, building permits, and aerial photographs of Epstein's private island, Little St. James, in the U.S. Virgin Islands. Includes worker testimonies about the compound.",
      documentType: "fbi report",
      dataSet: "8",
      sourceUrl: "https://www.justice.gov/epstein/doj-disclosures/data-set-8-files",
      datePublished: "2026-01-30",
      dateOriginal: "1998-2019",
      pageCount: 156,
      isRedacted: true,
      keyExcerpt: "The 70-acre island included a main residence, guest houses, a temple-like structure, and a network of underground facilities. Workers described strict rules about avoiding certain areas.",
      tags: ["island", "Little St. James", "property", "Virgin Islands"],
    },
    {
      title: "Alan Dershowitz Deposition - Counter-Claims",
      description: "Deposition of attorney Alan Dershowitz taken as part of defamation counter-claims related to the Epstein case. Dershowitz denied all allegations and detailed his legal representation of Epstein.",
      documentType: "deposition",
      dataSet: "2",
      sourceUrl: "https://www.justice.gov/epstein/court-records",
      datePublished: "2024-01-03",
      dateOriginal: "2016-06-15",
      pageCount: 187,
      isRedacted: true,
      keyExcerpt: "Dershowitz testified he kept his underwear on during any massage at Epstein's residence and categorically denied any sexual contact with any minor.",
      tags: ["deposition", "Dershowitz", "legal defense"],
    },
  ];

  const createdDocs = [];
  for (const d of documentData) {
    const [created] = await db.insert(documents).values(d).returning();
    createdDocs.push(created);
  }

  const personDocLinks = [
    { personIndex: 0, docIndex: 0, mentionType: "subject", context: "Owner and primary passenger of the aircraft" },
    { personIndex: 0, docIndex: 3, mentionType: "subject", context: "Defendant in the non-prosecution agreement" },
    { personIndex: 0, docIndex: 4, mentionType: "subject", context: "Subject of all victim interviews" },
    { personIndex: 0, docIndex: 5, mentionType: "subject", context: "Owner of the contact book" },
    { personIndex: 0, docIndex: 6, mentionType: "subject", context: "Target of grand jury investigation" },
    { personIndex: 0, docIndex: 7, mentionType: "subject", context: "Deceased individual in surveillance footage" },
    { personIndex: 0, docIndex: 9, mentionType: "subject", context: "Owner of searched properties" },
    { personIndex: 0, docIndex: 10, mentionType: "subject", context: "Account holder" },
    { personIndex: 0, docIndex: 11, mentionType: "subject", context: "Sender/recipient of emails" },
    { personIndex: 0, docIndex: 12, mentionType: "subject", context: "Subject of seized photographs" },
    { personIndex: 0, docIndex: 15, mentionType: "subject", context: "Holder of fake passport" },
    { personIndex: 0, docIndex: 18, mentionType: "subject", context: "Owner of Little St. James" },
    { personIndex: 1, docIndex: 1, mentionType: "defendant", context: "Defendant in defamation lawsuit" },
    { personIndex: 1, docIndex: 2, mentionType: "subject", context: "Deponent in defamation case" },
    { personIndex: 1, docIndex: 0, mentionType: "mentioned", context: "Listed as passenger on multiple flights" },
    { personIndex: 1, docIndex: 11, mentionType: "subject", context: "Sender/recipient of correspondence" },
    { personIndex: 1, docIndex: 12, mentionType: "mentioned", context: "Appeared in photographs with various individuals" },
    { personIndex: 1, docIndex: 17, mentionType: "defendant", context: "Defendant in federal trial" },
    { personIndex: 2, docIndex: 0, mentionType: "mentioned", context: "Listed on multiple flight manifests" },
    { personIndex: 2, docIndex: 12, mentionType: "mentioned", context: "Photographed with Epstein" },
    { personIndex: 2, docIndex: 5, mentionType: "mentioned", context: "Listed in contact directory" },
    { personIndex: 3, docIndex: 12, mentionType: "mentioned", context: "Photographed with Maxwell" },
    { personIndex: 3, docIndex: 5, mentionType: "mentioned", context: "Listed in contact book" },
    { personIndex: 4, docIndex: 8, mentionType: "mentioned", context: "Described in witness testimony" },
    { personIndex: 4, docIndex: 0, mentionType: "mentioned", context: "Listed in flight logs" },
    { personIndex: 4, docIndex: 1, mentionType: "mentioned", context: "Named in Giuffre deposition" },
    { personIndex: 5, docIndex: 1, mentionType: "subject", context: "Plaintiff and key deponent" },
    { personIndex: 5, docIndex: 4, mentionType: "mentioned", context: "Provided statements to FBI" },
    { personIndex: 5, docIndex: 13, mentionType: "mentioned", context: "Submitted victim impact statement" },
    { personIndex: 6, docIndex: 3, mentionType: "mentioned", context: "Part of Epstein's defense team" },
    { personIndex: 6, docIndex: 19, mentionType: "subject", context: "Deponent in counter-claims" },
    { personIndex: 6, docIndex: 5, mentionType: "mentioned", context: "Listed in contact book" },
    { personIndex: 7, docIndex: 0, mentionType: "mentioned", context: "Listed on flight manifests" },
    { personIndex: 7, docIndex: 5, mentionType: "mentioned", context: "Listed in contact directory" },
    { personIndex: 8, docIndex: 4, mentionType: "mentioned", context: "Named in victim statements" },
    { personIndex: 8, docIndex: 3, mentionType: "mentioned", context: "Named as co-conspirator given immunity" },
    { personIndex: 9, docIndex: 16, mentionType: "mentioned", context: "Granted Epstein power of attorney" },
    { personIndex: 9, docIndex: 10, mentionType: "mentioned", context: "Financial transactions documented" },
    { personIndex: 10, docIndex: 3, mentionType: "mentioned", context: "U.S. Attorney who authorized the plea deal" },
    { personIndex: 11, docIndex: 0, mentionType: "mentioned", context: "Listed as flight passenger" },
    { personIndex: 11, docIndex: 12, mentionType: "mentioned", context: "Appeared in seized photographs" },
    { personIndex: 12, docIndex: 12, mentionType: "mentioned", context: "Photographed with Maxwell" },
    { personIndex: 12, docIndex: 1, mentionType: "mentioned", context: "Named in Giuffre deposition" },
    { personIndex: 13, docIndex: 3, mentionType: "mentioned", context: "Named as co-conspirator given immunity" },
    { personIndex: 13, docIndex: 4, mentionType: "mentioned", context: "Named in victim interview reports" },
    { personIndex: 14, docIndex: 8, mentionType: "subject", context: "Key deponent and witness" },
    { personIndex: 14, docIndex: 4, mentionType: "mentioned", context: "Provided statements to FBI" },
    { personIndex: 15, docIndex: 1, mentionType: "mentioned", context: "Named in Giuffre deposition testimony" },
    { personIndex: 16, docIndex: 1, mentionType: "mentioned", context: "Named in Giuffre deposition testimony" },
    { personIndex: 17, docIndex: 3, mentionType: "mentioned", context: "Named as co-conspirator given immunity" },
    { personIndex: 18, docIndex: 3, mentionType: "mentioned", context: "Named as co-conspirator given immunity" },
    { personIndex: 19, docIndex: 12, mentionType: "mentioned", context: "Photos found on his phone in DOJ release" },
  ];

  for (const link of personDocLinks) {
    await db.insert(personDocuments).values({
      personId: createdPersons[link.personIndex].id,
      documentId: createdDocs[link.docIndex].id,
      mentionType: link.mentionType,
      context: link.context,
    });
  }

  const connectionData = [
    { p1: 0, p2: 1, type: "co-conspirator", desc: "Maxwell convicted as co-conspirator in Epstein's sex trafficking operation. Close personal and professional relationship spanning decades.", strength: 3 },
    { p1: 0, p2: 2, type: "social connection", desc: "Clinton appeared on Epstein flight logs. Photographed together. No accusations of misconduct with minors.", strength: 2 },
    { p1: 0, p2: 3, type: "social connection", desc: "Trump and Epstein were part of the same Palm Beach social circle. Trump later banned Epstein from Mar-a-Lago.", strength: 1 },
    { p1: 0, p2: 4, type: "social connection", desc: "Prince Andrew visited Epstein properties and was named in victim depositions. Subject of civil lawsuit.", strength: 3 },
    { p1: 0, p2: 5, type: "victim testimony", desc: "Giuffre alleges she was trafficked by Epstein starting at age 15. Central accuser in multiple proceedings.", strength: 3 },
    { p1: 0, p2: 6, type: "legal counsel", desc: "Dershowitz served as Epstein's defense attorney and helped negotiate the 2008 plea deal.", strength: 2 },
    { p1: 0, p2: 7, type: "business associate", desc: "Brunel allegedly procured young women for Epstein through his modeling agencies MC2 and Karin Models.", strength: 3 },
    { p1: 0, p2: 8, type: "employee", desc: "Kellen served as Epstein's personal assistant and was named as a co-conspirator in the 2008 NPA.", strength: 3 },
    { p1: 0, p2: 9, type: "business associate", desc: "Wexner was Epstein's primary financial client and gave him extensive power of attorney over his wealth.", strength: 3 },
    { p1: 0, p2: 10, type: "legal counsel", desc: "Acosta oversaw the controversial 2008 plea agreement as U.S. Attorney for the Southern District of Florida.", strength: 2 },
    { p1: 0, p2: 13, type: "employee", desc: "Marcinkova reportedly brought to U.S. by Epstein. Later became pilot. Named in victim statements.", strength: 3 },
    { p1: 0, p2: 14, type: "victim testimony", desc: "Sjoberg recruited as college student to work for Epstein. Key witness in depositions.", strength: 2 },
    { p1: 1, p2: 4, type: "social connection", desc: "Maxwell and Prince Andrew had a longstanding friendship. She allegedly introduced him to Giuffre.", strength: 2 },
    { p1: 1, p2: 5, type: "victim testimony", desc: "Giuffre filed defamation lawsuit against Maxwell, whose unsealing produced many of the public documents.", strength: 3 },
    { p1: 1, p2: 7, type: "business associate", desc: "Maxwell and Brunel collaborated in Epstein's social circle and modeling industry connections.", strength: 2 },
    { p1: 1, p2: 12, type: "social connection", desc: "Maxwell photographed with Copperfield at social events documented in seized materials.", strength: 1 },
    { p1: 4, p2: 5, type: "victim testimony", desc: "Giuffre alleged she was trafficked to Prince Andrew on multiple occasions. Andrew settled civil lawsuit.", strength: 3 },
    { p1: 4, p2: 14, type: "social connection", desc: "Sjoberg testified about encounter with Prince Andrew at Epstein's New York residence.", strength: 2 },
    { p1: 5, p2: 15, type: "victim testimony", desc: "Giuffre named Richardson in deposition as someone she was directed to provide services to.", strength: 2 },
    { p1: 5, p2: 16, type: "victim testimony", desc: "Giuffre named Mitchell in her deposition testimony as someone she was sent to.", strength: 2 },
    { p1: 0, p2: 11, type: "social connection", desc: "Spacey photographed as passenger on Epstein's aircraft. Named in flight logs.", strength: 1 },
    { p1: 0, p2: 17, type: "employee", desc: "Ross worked as Epstein employee. Named as co-conspirator given immunity in 2008 plea.", strength: 2 },
    { p1: 0, p2: 18, type: "employee", desc: "Groff served as Epstein's executive assistant for many years. Named in 2008 NPA.", strength: 2 },
    { p1: 3, p2: 19, type: "political ally", desc: "Bannon served as Trump's Chief Strategist. Photos on his phone included in DOJ releases.", strength: 1 },
    { p1: 0, p2: 15, type: "social connection", desc: "Richardson visited Epstein properties according to victim testimony and flight records.", strength: 1 },
    { p1: 0, p2: 16, type: "social connection", desc: "Mitchell named in victim depositions and referenced in contact records.", strength: 1 },
  ];

  for (const conn of connectionData) {
    await db.insert(connections).values({
      personId1: createdPersons[conn.p1].id,
      personId2: createdPersons[conn.p2].id,
      connectionType: conn.type,
      description: conn.desc,
      strength: conn.strength,
    });
  }

  const timelineData = [
    { date: "1953-01-20", title: "Jeffrey Epstein Born", description: "Jeffrey Edward Epstein born in Brooklyn, New York to a middle-class family. He would later attend Cooper Union and NYU but did not obtain a degree.", category: "relationship", significance: 1 },
    { date: "1986-01-01", title: "Epstein Establishes Financial Firm", description: "Epstein establishes his own financial management firm, J. Epstein & Co., catering exclusively to clients with net worth over $1 billion.", category: "relationship", significance: 1 },
    { date: "1991-01-01", title: "Epstein Meets Ghislaine Maxwell", description: "Epstein begins his relationship with Ghislaine Maxwell, daughter of media magnate Robert Maxwell. She becomes his close companion and later his alleged co-conspirator.", category: "relationship", significance: 2 },
    { date: "1996-01-01", title: "Epstein Purchases Little St. James Island", description: "Epstein purchases the 70-acre private island Little St. James in the U.S. Virgin Islands, where he builds a compound that would later become central to trafficking allegations.", category: "relationship", significance: 2 },
    { date: "1998-01-01", title: "Les Wexner Power of Attorney", description: "Billionaire Les Wexner grants Epstein sweeping power of attorney over his financial affairs. Wexner's Manhattan mansion is transferred to Epstein.", category: "relationship", significance: 2 },
    { date: "2000-02-12", title: "Virginia Roberts Recruited", description: "Virginia Roberts (later Giuffre), age 15, recruited at Mar-a-Lago by Ghislaine Maxwell while working as a spa attendant. She alleges she was subsequently trafficked for several years.", category: "investigation", significance: 3 },
    { date: "2005-03-01", title: "Palm Beach Police Investigation Begins", description: "Palm Beach, Florida police begin investigating Epstein after a parent reports that her 14-year-old stepdaughter was paid $300 for a sexual encounter at Epstein's mansion.", category: "investigation", significance: 3 },
    { date: "2006-05-01", title: "FBI Opens Federal Investigation", description: "The FBI opens a federal investigation into Epstein's activities. Agents identify dozens of potential victims, many of whom were minors at the time of the alleged abuse.", category: "investigation", significance: 3 },
    { date: "2007-06-01", title: "53-Page Federal Indictment Prepared", description: "Federal prosecutors prepare a 53-page indictment against Epstein on sex trafficking charges. The case would ultimately be settled through a plea deal rather than going to trial.", category: "legal", significance: 2 },
    { date: "2008-06-30", title: "Controversial Non-Prosecution Agreement Signed", description: "U.S. Attorney Alexander Acosta approves a controversial plea deal. Epstein pleads guilty to state prostitution charges, serves 13 months in county jail with work release. Federal charges dropped. Four co-conspirators given immunity.", category: "legal", significance: 3 },
    { date: "2008-07-01", title: "Epstein Begins Jail Sentence", description: "Epstein begins serving his 18-month sentence at the Palm Beach County Stockade. He is granted work release privileges allowing him to leave jail for up to 12 hours a day, six days a week.", category: "legal", significance: 2 },
    { date: "2009-07-22", title: "Epstein Released from Jail", description: "Epstein released from Palm Beach County Stockade after serving approximately 13 months. Registers as a sex offender. Returns to his residences and resumes social activities.", category: "legal", significance: 2 },
    { date: "2014-12-30", title: "Virginia Giuffre Files Lawsuit", description: "Virginia Roberts Giuffre files a civil lawsuit joining existing litigation against Epstein, naming Prince Andrew and Alan Dershowitz as individuals she was trafficked to.", category: "legal", significance: 3 },
    { date: "2015-01-01", title: "Giuffre v. Maxwell Defamation Suit Filed", description: "Virginia Giuffre files a defamation lawsuit against Ghislaine Maxwell after Maxwell publicly called her a liar. This case generates many of the documents later unsealed.", category: "legal", significance: 3 },
    { date: "2016-04-22", title: "Maxwell Deposition Taken Under Seal", description: "Ghislaine Maxwell gives a 418-page deposition in the Giuffre defamation case. She denies all allegations. The deposition is sealed but later released as part of document unsealing.", category: "court", significance: 2 },
    { date: "2017-05-25", title: "Maxwell Defamation Case Settled", description: "The Giuffre v. Maxwell defamation case is settled for an undisclosed amount. The sealed documents from the case become the subject of future unsealing battles.", category: "court", significance: 2 },
    { date: "2018-11-28", title: "Miami Herald Investigation Published", description: "Miami Herald reporter Julie K. Brown publishes 'Perversion of Justice,' a landmark investigative series exposing the details of Epstein's 2008 plea deal and the breadth of his alleged crimes.", category: "investigation", significance: 3 },
    { date: "2019-07-06", title: "Epstein Arrested on Federal Charges", description: "Jeffrey Epstein arrested at Teterboro Airport in New Jersey by FBI agents and NYPD detectives on federal charges of sex trafficking of minors. FBI raids his Manhattan mansion, finding evidence including photos, CDs, cash, and a fake passport.", category: "arrest", significance: 3 },
    { date: "2019-07-08", title: "Indictment Unsealed - SDNY", description: "The Southern District of New York unseals the indictment charging Epstein with sex trafficking of minors and conspiracy to engage in sex trafficking. Prosecutors allege a pattern of abuse spanning years.", category: "court", significance: 3 },
    { date: "2019-07-18", title: "Bail Denied", description: "Federal judge denies Epstein bail, ruling he poses a flight risk and danger to the community. Epstein ordered held at Metropolitan Correctional Center in Manhattan.", category: "court", significance: 2 },
    { date: "2019-07-23", title: "First Suicide Attempt", description: "Epstein found semi-conscious with marks on his neck in his cell at MCC. Placed on suicide watch briefly, then removed after approximately a week at his lawyers' request.", category: "investigation", significance: 2 },
    { date: "2019-08-10", title: "Jeffrey Epstein Found Dead in Cell", description: "Jeffrey Epstein found unresponsive in his cell at the Metropolitan Correctional Center in Manhattan. Pronounced dead at New York Presbyterian-Lower Manhattan Hospital. Death ruled suicide by hanging by the NYC Medical Examiner.", category: "death", significance: 3 },
    { date: "2019-08-12", title: "Alexander Acosta Resigns", description: "Former U.S. Attorney Alexander Acosta resigns as Secretary of Labor amid renewed scrutiny of the 2008 plea deal he authorized for Epstein.", category: "political", significance: 2 },
    { date: "2020-07-02", title: "Ghislaine Maxwell Arrested", description: "Ghislaine Maxwell arrested by FBI at her home in Bradford, New Hampshire, charged with conspiracy to entice minors to travel for illegal sex acts, sex trafficking of minors, and perjury.", category: "arrest", significance: 3 },
    { date: "2021-12-29", title: "Maxwell Found Guilty", description: "After a month-long trial, a federal jury finds Ghislaine Maxwell guilty on five of six counts including sex trafficking of a minor, conspiracy, and transporting a minor to engage in illegal sexual activity.", category: "court", significance: 3 },
    { date: "2022-02-19", title: "Jean-Luc Brunel Found Dead", description: "French modeling agent Jean-Luc Brunel found dead by hanging in his Paris prison cell while awaiting trial on charges of rape and sex trafficking of minors linked to Epstein.", category: "death", significance: 2 },
    { date: "2022-02-15", title: "Prince Andrew Settles Civil Lawsuit", description: "Prince Andrew settles Virginia Giuffre's civil sexual assault lawsuit for an undisclosed amount, estimated at approximately $12 million. He denies all allegations.", category: "legal", significance: 3 },
    { date: "2022-06-28", title: "Maxwell Sentenced to 20 Years", description: "Ghislaine Maxwell sentenced to 20 years in federal prison for her role in Epstein's sex trafficking operation. Judge describes her crimes as 'heinous and predatory.'", category: "court", significance: 3 },
    { date: "2024-01-03", title: "First Major Document Unsealing", description: "Court documents from the Maxwell defamation case unsealed, revealing names of nearly 200 individuals including former presidents, royalty, and celebrities. Most named individuals face no accusations.", category: "disclosure", significance: 3 },
    { date: "2025-09-01", title: "House Oversight Committee Release", description: "House Committee on Oversight releases 33,295 pages of Epstein-related records provided by the DOJ, including surveillance footage from the night of Epstein's death.", category: "disclosure", significance: 3 },
    { date: "2025-11-19", title: "Epstein Files Transparency Act Signed", description: "President Trump signs the Epstein Files Transparency Act, mandating the DOJ release all unclassified Epstein-related records within 30 days.", category: "political", significance: 3 },
    { date: "2025-12-19", title: "First DOJ Document Release", description: "DOJ releases tens of thousands of records including photographs, contact lists, flight logs, business records and memos, and court documents. Many files heavily redacted, drawing bipartisan criticism.", category: "disclosure", significance: 3 },
    { date: "2026-01-30", title: "Major DOJ Release - 3 Million Pages", description: "DOJ publishes over 3 million additional pages including 2,000 videos and 180,000 images. Redactions limited to victim protection. Notable individuals and politicians not redacted.", category: "disclosure", significance: 3 },
  ];

  for (const event of timelineData) {
    await db.insert(timelineEvents).values(event);
  }

  console.log("Database seeded successfully!");
  console.log(`  - ${personData.length} persons`);
  console.log(`  - ${documentData.length} documents`);
  console.log(`  - ${personDocLinks.length} person-document links`);
  console.log(`  - ${connectionData.length} connections`);
  console.log(`  - ${timelineData.length} timeline events`);
}
